version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  api:
    build:
      context: ../chatbot-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      LOG_LEVEL: DEBUG
      DATABASE_URL: postgresql://user:password@db/chatbot_db
      OLLAMA_API_BASE: http://host.docker.internal:11434
    networks:
      - backend
      - frontend
  frontend:
    build:
      context: ../chatbot-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8000/api
    networks:
      - frontend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
